Extract transports creation into a factory
eXolnet/laravel-graylog pull request #3
Opened 2020-07-22 13:00 UTC by xel1045

- Aligned provided transports with exolnet/wp-graylog

# Description

That way, transport creation is centralized into a class with a single concern. This PR also align available transports based on `exolnet/wp-graylog`. Finally, this PR remove the usage of the `GRAYLOG_SECURE` parameter.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Units tests have been added to test the new `TransportFactory`.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2020-07-24 20:53 UTC, pgrenaud commented on README.md
> +Once installed, errors occurring in your code with a level higher or equals to the `GRAYLOG_LEVEL` will be sent to
@xel1045 Cette variable d'environnement n'existe pas pour eXolnet/laravel-graylog.

2020-07-24 20:54 UTC, pgrenaud requested changes
Correction à faire. Voir le commentaire.

2020-07-27 12:50 UTC, xel1045 commented on README.md
> +Once installed, errors occurring in your code with a level higher or equals to the `GRAYLOG_LEVEL` will be sent to
Oops! Tu as bien raison.

2020-07-27 13:23 UTC, pgrenaud commented on README.md
> +## Usage
@xel1045 Tu as laissé une section "Usage" vide. 😅 Tu peux l'enlever?

2020-07-27 14:04 UTC, xel1045 commented on README.md
> +## Usage
La section «Usage» contient la section «Supported Transports»

2020-07-27 14:08 UTC, pgrenaud approved these changes

2020-07-27 14:44 UTC, merged